export class NightVision {
    constructor(target: any, props?: {});
    _data: any;
    _scripts: any;
    hub: any;
    meta: any;
    scan: any;
    events: any;
    scriptHub: any;
    root: HTMLElement;
    comp: any;
    set id(arg: any);
    get id(): any;
    set width(arg: any);
    get width(): any;
    set height(arg: any);
    get height(): any;
    set colors(arg: any);
    get colors(): any;
    set showLogo(arg: any);
    get showLogo(): any;
    set scripts(arg: any);
    get scripts(): any;
    set data(arg: any);
    get data(): any;
    set config(arg: any);
    get config(): any;
    set indexBased(arg: any);
    get indexBased(): any;
    set timezone(arg: any);
    get timezone(): any;
    get layout(): any;
    set range(arg: any);
    get range(): any;
    set cursor(arg: any);
    get cursor(): any;
    update(type?: string, opt?: {}): void;
    fullReset(): void;
}
